options:
  nginx:
    default: True
    type: boolean
    description: Configures nginx and gunicron for the flask application.
  flask-port:
    default: 8000
    type: int
    description: Flask listening port
  workers:
    default: 2
    type: int
    description: Amount of gunicorn workers